### ISSUE TITLE
Minimize "pollution" for accurate measurements

### ISSUE THREAD

**Issue by f-masche** [haensl/js-performance#31]
Do not do anything except running the test during measurement.
```javascript
  let end;
  const start = process.hrtime();
  fn(d);
  end = process.hrtime(start);
```

**Comment by haensl** [comment]
Since we were talking about this today...
...coincidentally I read stuff about DBC *(Design By Contract)* today, which essentially states: *"Don't do parameter checks, but let shit hit the fan."* It, however, suggests contracts, e.g. function parameters, be documented *(otherwise where would be the contract?)*.

We would therefore need to agree upon documenting function params, but otherwise throw all type checks out the window.

I was thinking this project might be a good opportunity to give this design paradigm a try, you in?

**Comment by f-masche** [comment]
Where did you read that? I don't think documentation will make your code less error prone. I would rather invest the time in writing good tests than in writing documentation.
If we do the extra work I would go with [FlowTypes](https://flowtype.org/) and have the extra benefit of static type checking.

**Comment by haensl** [comment]
Nah, no type-stuff on the beautiful JS 👎  for FlowTypes.
I read about DBC in *"The Pragmatic Programmer"*. And it's not about writing full fledged docs. Rather, when you write a function you add a signature comment above it, e.g.
```javascript
// @param foo: string
// @param bar: array
const doStuff = (foo, bar) => {
  //
};
```

**Comment by haensl** [comment]
PR open https://github.com/haensl/js-performance/pull/52

**Comment by haensl** [comment]
Done in v1.14.0
